### ISSUE TITLE
`nhdplusTools::get_nldi_characteristics` to be retired

### ISSUE THREAD

**Issue by dblodgett-usgs** [joshualerickson/gwavr#6]
Hi @joshualerickson -- I'm releasing a new version of nhdplusTools to CRAN. When I was running reverse dependency checks, I noticed that you are using `get_nldi_characteristics()`. 

Sometime in the next year, I expect to need to retire that function in favor of: https://doi-usgs.github.io/nhdplusTools/reference/get_catchment_characteristics.html

There's a ton more data available from that and we are planning on removing the characteristics end point from the NLDI. 

This will not happen for at least 9 months, but I wanted to note it since I saw it in the CRAN dependency checks.

**Comment by joshualerickson** [comment]
Thanks @dblodgett-usgs for the heads up on this! That looks pretty sweet 👌I’m in the process of updating the package so I’ll add it to the list. Thanks.
