### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by dblodgett-usgs** [joshualerickson/gwavr#8]
Hi @joshualerickson -- I'm trying to release an update to NHDPlusTools and a couple functions that I retired are still called in the version of gwavr that's on CRAN. Should I bring those back with a deprecated message or do you think you can get a new release out soon?

**Comment by dblodgett-usgs** [comment]
```
Package: gwavr
Check: dependencies in R code
New result: WARNING
  Missing or unexported objects:
    ‘nhdplusTools::get_huc12’ ‘nhdplusTools::get_huc8’
```

**Comment by joshualerickson** [comment]
Oh shoot, sorry Dave. I'm pretty sure I switched them but must not have submitted to CRAN. Traveling right now but should be able to get it sent tomorrow so no need to put as deprecated.

**Comment by dblodgett-usgs** [comment]
Right on - not a big rush on my end. Just let me know when you have it up and I'll resubmit.

From: Josh Erickson ***@***.***>
Sent: Thursday, May 9, 2024 4:20 PM
To: joshualerickson/gwavr ***@***.***>
Cc: Blodgett, David L ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [joshualerickson/gwavr] CRAN release? (Issue #8)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Oh shoot, sorry Dave. I'm pretty sure I switched them but must not have submitted to CRAN. Traveling right now but should be able to get it sent tomorrow so no need to put as deprecated.

-

**Comment by joshualerickson** [comment]
Hey @dblodgett-usgs, should be good to go but let me know if you run into any issues, thanks!

**Comment by dblodgett-usgs** [comment]
Thanks for the quick turn around!!
